// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_XT7MdTsgT5HwcuS1YBc7fpRXid8haw',
    appId: '1:62811631074:web:6322664645b87e4c645dbb',
    messagingSenderId: '62811631074',
    projectId: 'foodordering-7aee6',
    authDomain: 'foodordering-7aee6.firebaseapp.com',
    storageBucket: 'foodordering-7aee6.appspot.com',
    measurementId: 'G-9T09NBSXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGF1osvEdwP7VMoQB1UBMdkRz4Whu2qs',
    appId: '1:62811631074:android:73bc48cb0078dfaa645dbb',
    messagingSenderId: '62811631074',
    projectId: 'foodordering-7aee6',
    storageBucket: 'foodordering-7aee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIk5iy1acTe0e1xffNaCEC44Vwy_FQ-S4',
    appId: '1:62811631074:ios:b3ca6f12e82e9d54645dbb',
    messagingSenderId: '62811631074',
    projectId: 'foodordering-7aee6',
    storageBucket: 'foodordering-7aee6.appspot.com',
    iosBundleId: 'com.example.foodordering',
  );
}
